version: "3.8"

services:
  mongo1:
    image: mongo:latest
    container_name: mongo_container
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017'}]}) }" | mongosh --port 27017 --quiet &&
        mongorestore /dump
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30
    volumes:
      - "mongo_data:/data/db"
      - "mongo_config:/data/configdb"
      - "./dump:/dump"  # Mount the dump folder containing the BSON data
volumes:
  mongo_data:
  mongo_config: